apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-nginx-config
  namespace: tiny-llm
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      server {
        listen 30081;
        location / {
          proxy_pass http://tiny-llm-frontend.tiny-llm.svc.cluster.local:80;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }

      server {
        listen 30080;
        location / {
          proxy_pass https://argocd-server.argocd.svc.cluster.local:443;
          proxy_ssl_verify off;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }

      server {
        listen 30030;
        location / {
          proxy_pass http://grafana.observability.svc.cluster.local:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }

      server {
        listen 30090;
        location / {
          proxy_pass http://prometheus.observability.svc.cluster.local:9090;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
