apiVersion: v1
kind: Service
metadata:
  name: gateway-nginx
  namespace: tiny-llm
spec:
  type: NodePort
  selector:
    app: gateway-nginx
  ports:
    - name: frontend
      port: 30081
      targetPort: 30081
      nodePort: 30081
    - name: argocd
      port: 30080
      targetPort: 30080
      nodePort: 30080
    - name: grafana
      port: 30030
      targetPort: 30030
      nodePort: 30030
    - name: prometheus
      port: 30090
      targetPort: 30090
      nodePort: 30090
